namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyDoan
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.grpDoan = new System.Windows.Forms.GroupBox();
            this.lbl1 = new System.Windows.Forms.Label();
            this.txtMaDoan = new System.Windows.Forms.TextBox();
            this.lbl2 = new System.Windows.Forms.Label();
            this.txtTenCQ = new System.Windows.Forms.TextBox();
            this.lbl3 = new System.Windows.Forms.Label();
            this.txtDiaChi = new System.Windows.Forms.TextBox();
            this.lbl4 = new System.Windows.Forms.Label();
            this.txtDT = new System.Windows.Forms.TextBox();
            this.lbl5 = new System.Windows.Forms.Label();
            this.txtDaiDien = new System.Windows.Forms.TextBox();
            this.grpDangKy = new System.Windows.Forms.GroupBox();
            this.lbl6 = new System.Windows.Forms.Label();
            this.txtSo = new System.Windows.Forms.TextBox();
            this.lbl7 = new System.Windows.Forms.Label();
            this.cboTour = new System.Windows.Forms.ComboBox();
            this.lbl8 = new System.Windows.Forms.Label();
            this.dtDi = new System.Windows.Forms.DateTimePicker();
            this.lbl9 = new System.Windows.Forms.Label();
            this.numNguoi = new System.Windows.Forms.NumericUpDown();
            this.lbl10 = new System.Windows.Forms.Label();
            this.txtDon = new System.Windows.Forms.TextBox();
            this.lbl11 = new System.Windows.Forms.Label();
            this.numCoc = new System.Windows.Forms.NumericUpDown();
            this.chkBH = new System.Windows.Forms.CheckBox();
            this.lbl12 = new System.Windows.Forms.Label();
            this.lblKetThuc = new System.Windows.Forms.Label();
            this.lbl13 = new System.Windows.Forms.Label();
            this.lblTong = new System.Windows.Forms.Label();
            this.lbl14 = new System.Windows.Forms.Label();
            this.dgvThanhVien = new System.Windows.Forms.DataGridView();
            this.btnDangKy = new System.Windows.Forms.Button();
            this.btnHuy = new System.Windows.Forms.Button();
            this.lbl15 = new System.Windows.Forms.Label();
            this.dgv = new System.Windows.Forms.DataGridView();
            this.btnDong = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.numNguoi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvThanhVien)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgv)).BeginInit();
            this.SuspendLayout();
            this.grpDoan.Name = "grpDoan";
            this.grpDoan.Location = new System.Drawing.Point(10, 10);
            this.grpDoan.Size = new System.Drawing.Size(430, 185);
            this.grpDoan.Text = "Thông tin đoàn khách";
            this.Controls.Add(this.grpDoan);
            this.lbl1.Name = "lbl1";
            this.lbl1.Location = new System.Drawing.Point(15, 28);
            this.lbl1.Text = "Mã đoàn:";
            this.lbl1.AutoSize = true;
            this.grpDoan.Controls.Add(this.lbl1);
            this.txtMaDoan.Name = "txtMaDoan";
            this.txtMaDoan.Location = new System.Drawing.Point(120, 25);
            this.txtMaDoan.Size = new System.Drawing.Size(150, 22);
            this.grpDoan.Controls.Add(this.txtMaDoan);
            this.lbl2.Name = "lbl2";
            this.lbl2.Location = new System.Drawing.Point(15, 58);
            this.lbl2.Text = "Cơ quan / gia đình:";
            this.lbl2.AutoSize = true;
            this.grpDoan.Controls.Add(this.lbl2);
            this.txtTenCQ.Name = "txtTenCQ";
            this.txtTenCQ.Location = new System.Drawing.Point(120, 55);
            this.txtTenCQ.Size = new System.Drawing.Size(295, 22);
            this.grpDoan.Controls.Add(this.txtTenCQ);
            this.lbl3.Name = "lbl3";
            this.lbl3.Location = new System.Drawing.Point(15, 88);
            this.lbl3.Text = "Địa chỉ:";
            this.lbl3.AutoSize = true;
            this.grpDoan.Controls.Add(this.lbl3);
            this.txtDiaChi.Name = "txtDiaChi";
            this.txtDiaChi.Location = new System.Drawing.Point(120, 85);
            this.txtDiaChi.Size = new System.Drawing.Size(295, 22);
            this.grpDoan.Controls.Add(this.txtDiaChi);
            this.lbl4.Name = "lbl4";
            this.lbl4.Location = new System.Drawing.Point(15, 118);
            this.lbl4.Text = "Điện thoại:";
            this.lbl4.AutoSize = true;
            this.grpDoan.Controls.Add(this.lbl4);
            this.txtDT.Name = "txtDT";
            this.txtDT.Location = new System.Drawing.Point(120, 115);
            this.txtDT.Size = new System.Drawing.Size(150, 22);
            this.grpDoan.Controls.Add(this.txtDT);
            this.lbl5.Name = "lbl5";
            this.lbl5.Location = new System.Drawing.Point(15, 148);
            this.lbl5.Text = "Người đại diện:";
            this.lbl5.AutoSize = true;
            this.grpDoan.Controls.Add(this.lbl5);
            this.txtDaiDien.Name = "txtDaiDien";
            this.txtDaiDien.Location = new System.Drawing.Point(120, 145);
            this.txtDaiDien.Size = new System.Drawing.Size(295, 22);
            this.grpDoan.Controls.Add(this.txtDaiDien);
            this.grpDangKy.Name = "grpDangKy";
            this.grpDangKy.Location = new System.Drawing.Point(450, 10);
            this.grpDangKy.Size = new System.Drawing.Size(440, 185);
            this.grpDangKy.Text = "Đăng ký tour";
            this.Controls.Add(this.grpDangKy);
            this.lbl6.Name = "lbl6";
            this.lbl6.Location = new System.Drawing.Point(15, 28);
            this.lbl6.Text = "Số phiếu:";
            this.lbl6.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl6);
            this.txtSo.Name = "txtSo";
            this.txtSo.Location = new System.Drawing.Point(95, 25);
            this.txtSo.Size = new System.Drawing.Size(110, 22);
            this.grpDangKy.Controls.Add(this.txtSo);
            this.lbl7.Name = "lbl7";
            this.lbl7.Location = new System.Drawing.Point(220, 28);
            this.lbl7.Text = "Tour:";
            this.lbl7.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl7);
            this.cboTour.Name = "cboTour";
            this.cboTour.Location = new System.Drawing.Point(255, 25);
            this.cboTour.Size = new System.Drawing.Size(170, 22);
            this.cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTour.FormattingEnabled = true;
            this.grpDangKy.Controls.Add(this.cboTour);
            this.lbl8.Name = "lbl8";
            this.lbl8.Location = new System.Drawing.Point(15, 58);
            this.lbl8.Text = "Ngày đi:";
            this.lbl8.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl8);
            this.dtDi.Name = "dtDi";
            this.dtDi.Location = new System.Drawing.Point(95, 55);
            this.dtDi.Size = new System.Drawing.Size(110, 22);
            this.dtDi.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.grpDangKy.Controls.Add(this.dtDi);
            this.lbl9.Name = "lbl9";
            this.lbl9.Location = new System.Drawing.Point(220, 58);
            this.lbl9.Text = "Số người:";
            this.lbl9.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl9);
            this.numNguoi.Name = "numNguoi";
            this.numNguoi.Location = new System.Drawing.Point(285, 55);
            this.numNguoi.Size = new System.Drawing.Size(70, 22);
            this.numNguoi.Minimum = new decimal(new int[] { 13, 0, 0, 0 });
            this.numNguoi.Maximum = new decimal(new int[] { 1000, 0, 0, 0 });
            this.numNguoi.Value = new decimal(new int[] { 13, 0, 0, 0 });
            this.grpDangKy.Controls.Add(this.numNguoi);
            this.lbl10.Name = "lbl10";
            this.lbl10.Location = new System.Drawing.Point(15, 88);
            this.lbl10.Text = "Địa điểm đón:";
            this.lbl10.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl10);
            this.txtDon.Name = "txtDon";
            this.txtDon.Location = new System.Drawing.Point(95, 85);
            this.txtDon.Size = new System.Drawing.Size(330, 22);
            this.grpDangKy.Controls.Add(this.txtDon);
            this.lbl11.Name = "lbl11";
            this.lbl11.Location = new System.Drawing.Point(15, 118);
            this.lbl11.Text = "Tiền cọc:";
            this.lbl11.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl11);
            this.numCoc.Name = "numCoc";
            this.numCoc.Location = new System.Drawing.Point(95, 115);
            this.numCoc.Size = new System.Drawing.Size(110, 22);
            this.numCoc.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            this.numCoc.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numCoc.Value = new decimal(new int[] { 0, 0, 0, 0 });
            this.numCoc.ThousandsSeparator = true;
            this.grpDangKy.Controls.Add(this.numCoc);
            this.chkBH.Name = "chkBH";
            this.chkBH.Location = new System.Drawing.Point(225, 117);
            this.chkBH.Size = new System.Drawing.Size(120, 20);
            this.chkBH.Text = "Mua bảo hiểm";
            this.chkBH.UseVisualStyleBackColor = true;
            this.grpDangKy.Controls.Add(this.chkBH);
            this.lbl12.Name = "lbl12";
            this.lbl12.Location = new System.Drawing.Point(15, 150);
            this.lbl12.Text = "Kết thúc DK:";
            this.lbl12.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl12);
            this.lblKetThuc.Name = "lblKetThuc";
            this.lblKetThuc.Location = new System.Drawing.Point(95, 150);
            this.lblKetThuc.Text = "-";
            this.lblKetThuc.AutoSize = true;
            this.lblKetThuc.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.grpDangKy.Controls.Add(this.lblKetThuc);
            this.lbl13.Name = "lbl13";
            this.lbl13.Location = new System.Drawing.Point(200, 150);
            this.lbl13.Text = "Tổng dự kiến:";
            this.lbl13.AutoSize = true;
            this.grpDangKy.Controls.Add(this.lbl13);
            this.lblTong.Name = "lblTong";
            this.lblTong.Location = new System.Drawing.Point(285, 150);
            this.lblTong.Text = "0 đ";
            this.lblTong.AutoSize = true;
            this.lblTong.ForeColor = System.Drawing.Color.Maroon;
            this.lblTong.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.grpDangKy.Controls.Add(this.lblTong);
            this.lbl14.Name = "lbl14";
            this.lbl14.Location = new System.Drawing.Point(10, 205);
            this.lbl14.Text = "Danh sách người cùng đi (bắt buộc đủ số người khi mua bảo hiểm):";
            this.lbl14.AutoSize = true;
            this.Controls.Add(this.lbl14);
            this.dgvThanhVien.Name = "dgvThanhVien";
            this.dgvThanhVien.Location = new System.Drawing.Point(10, 225);
            this.dgvThanhVien.Size = new System.Drawing.Size(880, 150);
            this.dgvThanhVien.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvThanhVien.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvThanhVien.MultiSelect = false;
            this.dgvThanhVien.AllowUserToDeleteRows = false;
            this.dgvThanhVien.AllowUserToAddRows = true;
            this.dgvThanhVien.ReadOnly = false;
            this.Controls.Add(this.dgvThanhVien);
            this.btnDangKy.Name = "btnDangKy";
            this.btnDangKy.Location = new System.Drawing.Point(590, 385);
            this.btnDangKy.Size = new System.Drawing.Size(140, 30);
            this.btnDangKy.Text = "Lập phiếu đăng ký";
            this.btnDangKy.UseVisualStyleBackColor = true;
            this.Controls.Add(this.btnDangKy);
            this.btnHuy.Name = "btnHuy";
            this.btnHuy.Location = new System.Drawing.Point(740, 385);
            this.btnHuy.Size = new System.Drawing.Size(150, 30);
            this.btnHuy.Text = "Hủy phiếu (mất cọc)";
            this.btnHuy.UseVisualStyleBackColor = true;
            this.Controls.Add(this.btnHuy);
            this.lbl15.Name = "lbl15";
            this.lbl15.Location = new System.Drawing.Point(10, 425);
            this.lbl15.Text = "Các phiếu đăng ký đoàn:";
            this.lbl15.AutoSize = true;
            this.Controls.Add(this.lbl15);
            this.dgv.Name = "dgv";
            this.dgv.Location = new System.Drawing.Point(10, 445);
            this.dgv.Size = new System.Drawing.Size(880, 220);
            this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.ReadOnly = true;
            this.Controls.Add(this.dgv);
            this.btnDong.Name = "btnDong";
            this.btnDong.Location = new System.Drawing.Point(790, 678);
            this.btnDong.Size = new System.Drawing.Size(100, 30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.Controls.Add(this.btnDong);
            this.cboTour.SelectedIndexChanged += new System.EventHandler(this.TinhTong);
            this.dtDi.ValueChanged += new System.EventHandler(this.TinhTong);
            this.numNguoi.ValueChanged += new System.EventHandler(this.TinhTong);
            this.chkBH.CheckedChanged += new System.EventHandler(this.chkBH_CheckedChanged);
            this.btnDangKy.Click += new System.EventHandler(this.btnDangKy_Click);
            this.btnHuy.Click += new System.EventHandler(this.btnHuy_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(900, 720);
            this.Name = "FrmDangKyDoan";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Phiếu đăng ký theo đoàn";
            this.Load += new System.EventHandler(this.FrmDangKyDoan_Load);
            ((System.ComponentModel.ISupportInitialize)(this.numNguoi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvThanhVien)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgv)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.GroupBox grpDoan;
        private System.Windows.Forms.Label lbl1;
        private System.Windows.Forms.TextBox txtMaDoan;
        private System.Windows.Forms.Label lbl2;
        private System.Windows.Forms.TextBox txtTenCQ;
        private System.Windows.Forms.Label lbl3;
        private System.Windows.Forms.TextBox txtDiaChi;
        private System.Windows.Forms.Label lbl4;
        private System.Windows.Forms.TextBox txtDT;
        private System.Windows.Forms.Label lbl5;
        private System.Windows.Forms.TextBox txtDaiDien;
        private System.Windows.Forms.GroupBox grpDangKy;
        private System.Windows.Forms.Label lbl6;
        private System.Windows.Forms.TextBox txtSo;
        private System.Windows.Forms.Label lbl7;
        private System.Windows.Forms.ComboBox cboTour;
        private System.Windows.Forms.Label lbl8;
        private System.Windows.Forms.DateTimePicker dtDi;
        private System.Windows.Forms.Label lbl9;
        private System.Windows.Forms.NumericUpDown numNguoi;
        private System.Windows.Forms.Label lbl10;
        private System.Windows.Forms.TextBox txtDon;
        private System.Windows.Forms.Label lbl11;
        private System.Windows.Forms.NumericUpDown numCoc;
        private System.Windows.Forms.CheckBox chkBH;
        private System.Windows.Forms.Label lbl12;
        private System.Windows.Forms.Label lblKetThuc;
        private System.Windows.Forms.Label lbl13;
        private System.Windows.Forms.Label lblTong;
        private System.Windows.Forms.Label lbl14;
        private System.Windows.Forms.DataGridView dgvThanhVien;
        private System.Windows.Forms.Button btnDangKy;
        private System.Windows.Forms.Button btnHuy;
        private System.Windows.Forms.Label lbl15;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.Button btnDong;
    }
}
