namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tabDanhMuc = new System.Windows.Forms.TabControl();
            this.tabPT = new System.Windows.Forms.TabPage();
            this.tabDB = new System.Windows.Forms.TabPage();
            this.tabHDV = new System.Windows.Forms.TabPage();
            this.tabDTQ = new System.Windows.Forms.TabPage();
            this.dgvPT = new System.Windows.Forms.DataGridView();
            this.lbl1 = new System.Windows.Forms.Label();
            this.txtPTMa = new System.Windows.Forms.TextBox();
            this.lbl2 = new System.Windows.Forms.Label();
            this.txtPTTen = new System.Windows.Forms.TextBox();
            this.lbl3 = new System.Windows.Forms.Label();
            this.txtPTGhiChu = new System.Windows.Forms.TextBox();
            this.btnThemPT = new System.Windows.Forms.Button();
            this.dgvDB = new System.Windows.Forms.DataGridView();
            this.lbl4 = new System.Windows.Forms.Label();
            this.txtDBMa = new System.Windows.Forms.TextBox();
            this.lbl5 = new System.Windows.Forms.Label();
            this.txtDBTen = new System.Windows.Forms.TextBox();
            this.lbl6 = new System.Windows.Forms.Label();
            this.txtDBDiaChi = new System.Windows.Forms.TextBox();
            this.lbl7 = new System.Windows.Forms.Label();
            this.txtDBDT = new System.Windows.Forms.TextBox();
            this.btnThemDB = new System.Windows.Forms.Button();
            this.dgvHDV = new System.Windows.Forms.DataGridView();
            this.lbl8 = new System.Windows.Forms.Label();
            this.txtHDVMa = new System.Windows.Forms.TextBox();
            this.lbl9 = new System.Windows.Forms.Label();
            this.txtHDVTen = new System.Windows.Forms.TextBox();
            this.lbl10 = new System.Windows.Forms.Label();
            this.txtHDVDT = new System.Windows.Forms.TextBox();
            this.lbl11 = new System.Windows.Forms.Label();
            this.numLuong = new System.Windows.Forms.NumericUpDown();
            this.btnThemHDV = new System.Windows.Forms.Button();
            this.dgvDTQ = new System.Windows.Forms.DataGridView();
            this.lbl12 = new System.Windows.Forms.Label();
            this.txtDTQMa = new System.Windows.Forms.TextBox();
            this.lbl13 = new System.Windows.Forms.Label();
            this.txtDTQTen = new System.Windows.Forms.TextBox();
            this.lbl14 = new System.Windows.Forms.Label();
            this.txtDTQDiaDiem = new System.Windows.Forms.TextBox();
            this.lbl15 = new System.Windows.Forms.Label();
            this.txtDTQNoiDung = new System.Windows.Forms.TextBox();
            this.lbl16 = new System.Windows.Forms.Label();
            this.txtDTQYNghia = new System.Windows.Forms.TextBox();
            this.btnThemDTQ = new System.Windows.Forms.Button();
            this.btnDong = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPT)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvHDV)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numLuong)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDTQ)).BeginInit();
            this.SuspendLayout();
            this.tabDanhMuc.Name = "tabDanhMuc";
            this.tabDanhMuc.Location = new System.Drawing.Point(10, 10);
            this.tabDanhMuc.Size = new System.Drawing.Size(780, 450);
            this.Controls.Add(this.tabDanhMuc);
            this.tabPT.Name = "tabPT";
            this.tabPT.Location = new System.Drawing.Point(4, 22);
            this.tabPT.Size = new System.Drawing.Size(772, 424);
            this.tabPT.Text = "Phương tiện";
            this.tabPT.UseVisualStyleBackColor = true;
            this.tabPT.Padding = new System.Windows.Forms.Padding(3);
            this.tabDanhMuc.Controls.Add(this.tabPT);
            this.tabDB.Name = "tabDB";
            this.tabDB.Location = new System.Drawing.Point(4, 22);
            this.tabDB.Size = new System.Drawing.Size(772, 424);
            this.tabDB.Text = "Điểm bán vé";
            this.tabDB.UseVisualStyleBackColor = true;
            this.tabDB.Padding = new System.Windows.Forms.Padding(3);
            this.tabDanhMuc.Controls.Add(this.tabDB);
            this.tabHDV.Name = "tabHDV";
            this.tabHDV.Location = new System.Drawing.Point(4, 22);
            this.tabHDV.Size = new System.Drawing.Size(772, 424);
            this.tabHDV.Text = "Hướng dẫn viên";
            this.tabHDV.UseVisualStyleBackColor = true;
            this.tabHDV.Padding = new System.Windows.Forms.Padding(3);
            this.tabDanhMuc.Controls.Add(this.tabHDV);
            this.tabDTQ.Name = "tabDTQ";
            this.tabDTQ.Location = new System.Drawing.Point(4, 22);
            this.tabDTQ.Size = new System.Drawing.Size(772, 424);
            this.tabDTQ.Text = "Điểm tham quan";
            this.tabDTQ.UseVisualStyleBackColor = true;
            this.tabDTQ.Padding = new System.Windows.Forms.Padding(3);
            this.tabDanhMuc.Controls.Add(this.tabDTQ);
            this.dgvPT.Name = "dgvPT";
            this.dgvPT.Location = new System.Drawing.Point(10, 10);
            this.dgvPT.Size = new System.Drawing.Size(750, 220);
            this.dgvPT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPT.MultiSelect = false;
            this.dgvPT.AllowUserToDeleteRows = false;
            this.dgvPT.AllowUserToAddRows = false;
            this.dgvPT.ReadOnly = true;
            this.tabPT.Controls.Add(this.dgvPT);
            this.lbl1.Name = "lbl1";
            this.lbl1.Location = new System.Drawing.Point(15, 245);
            this.lbl1.Text = "Mã PT:";
            this.lbl1.AutoSize = true;
            this.tabPT.Controls.Add(this.lbl1);
            this.txtPTMa.Name = "txtPTMa";
            this.txtPTMa.Location = new System.Drawing.Point(90, 242);
            this.txtPTMa.Size = new System.Drawing.Size(130, 22);
            this.tabPT.Controls.Add(this.txtPTMa);
            this.lbl2.Name = "lbl2";
            this.lbl2.Location = new System.Drawing.Point(260, 245);
            this.lbl2.Text = "Tên PT:";
            this.lbl2.AutoSize = true;
            this.tabPT.Controls.Add(this.lbl2);
            this.txtPTTen.Name = "txtPTTen";
            this.txtPTTen.Location = new System.Drawing.Point(320, 242);
            this.txtPTTen.Size = new System.Drawing.Size(250, 22);
            this.tabPT.Controls.Add(this.txtPTTen);
            this.lbl3.Name = "lbl3";
            this.lbl3.Location = new System.Drawing.Point(15, 280);
            this.lbl3.Text = "Ghi chú:";
            this.lbl3.AutoSize = true;
            this.tabPT.Controls.Add(this.lbl3);
            this.txtPTGhiChu.Name = "txtPTGhiChu";
            this.txtPTGhiChu.Location = new System.Drawing.Point(90, 277);
            this.txtPTGhiChu.Size = new System.Drawing.Size(480, 22);
            this.tabPT.Controls.Add(this.txtPTGhiChu);
            this.btnThemPT.Name = "btnThemPT";
            this.btnThemPT.Location = new System.Drawing.Point(600, 272);
            this.btnThemPT.Size = new System.Drawing.Size(100, 30);
            this.btnThemPT.Text = "Thêm";
            this.btnThemPT.UseVisualStyleBackColor = true;
            this.tabPT.Controls.Add(this.btnThemPT);
            this.dgvDB.Name = "dgvDB";
            this.dgvDB.Location = new System.Drawing.Point(10, 10);
            this.dgvDB.Size = new System.Drawing.Size(750, 220);
            this.dgvDB.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDB.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDB.MultiSelect = false;
            this.dgvDB.AllowUserToDeleteRows = false;
            this.dgvDB.AllowUserToAddRows = false;
            this.dgvDB.ReadOnly = true;
            this.tabDB.Controls.Add(this.dgvDB);
            this.lbl4.Name = "lbl4";
            this.lbl4.Location = new System.Drawing.Point(15, 245);
            this.lbl4.Text = "Mã điểm bán:";
            this.lbl4.AutoSize = true;
            this.tabDB.Controls.Add(this.lbl4);
            this.txtDBMa.Name = "txtDBMa";
            this.txtDBMa.Location = new System.Drawing.Point(100, 242);
            this.txtDBMa.Size = new System.Drawing.Size(120, 22);
            this.tabDB.Controls.Add(this.txtDBMa);
            this.lbl5.Name = "lbl5";
            this.lbl5.Location = new System.Drawing.Point(260, 245);
            this.lbl5.Text = "Tên điểm bán:";
            this.lbl5.AutoSize = true;
            this.tabDB.Controls.Add(this.lbl5);
            this.txtDBTen.Name = "txtDBTen";
            this.txtDBTen.Location = new System.Drawing.Point(350, 242);
            this.txtDBTen.Size = new System.Drawing.Size(220, 22);
            this.tabDB.Controls.Add(this.txtDBTen);
            this.lbl6.Name = "lbl6";
            this.lbl6.Location = new System.Drawing.Point(15, 280);
            this.lbl6.Text = "Địa chỉ:";
            this.lbl6.AutoSize = true;
            this.tabDB.Controls.Add(this.lbl6);
            this.txtDBDiaChi.Name = "txtDBDiaChi";
            this.txtDBDiaChi.Location = new System.Drawing.Point(100, 277);
            this.txtDBDiaChi.Size = new System.Drawing.Size(470, 22);
            this.tabDB.Controls.Add(this.txtDBDiaChi);
            this.lbl7.Name = "lbl7";
            this.lbl7.Location = new System.Drawing.Point(15, 315);
            this.lbl7.Text = "Điện thoại:";
            this.lbl7.AutoSize = true;
            this.tabDB.Controls.Add(this.lbl7);
            this.txtDBDT.Name = "txtDBDT";
            this.txtDBDT.Location = new System.Drawing.Point(100, 312);
            this.txtDBDT.Size = new System.Drawing.Size(150, 22);
            this.tabDB.Controls.Add(this.txtDBDT);
            this.btnThemDB.Name = "btnThemDB";
            this.btnThemDB.Location = new System.Drawing.Point(600, 272);
            this.btnThemDB.Size = new System.Drawing.Size(100, 30);
            this.btnThemDB.Text = "Thêm";
            this.btnThemDB.UseVisualStyleBackColor = true;
            this.tabDB.Controls.Add(this.btnThemDB);
            this.dgvHDV.Name = "dgvHDV";
            this.dgvHDV.Location = new System.Drawing.Point(10, 10);
            this.dgvHDV.Size = new System.Drawing.Size(750, 220);
            this.dgvHDV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvHDV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvHDV.MultiSelect = false;
            this.dgvHDV.AllowUserToDeleteRows = false;
            this.dgvHDV.AllowUserToAddRows = false;
            this.dgvHDV.ReadOnly = true;
            this.tabHDV.Controls.Add(this.dgvHDV);
            this.lbl8.Name = "lbl8";
            this.lbl8.Location = new System.Drawing.Point(15, 245);
            this.lbl8.Text = "Mã HDV:";
            this.lbl8.AutoSize = true;
            this.tabHDV.Controls.Add(this.lbl8);
            this.txtHDVMa.Name = "txtHDVMa";
            this.txtHDVMa.Location = new System.Drawing.Point(100, 242);
            this.txtHDVMa.Size = new System.Drawing.Size(120, 22);
            this.tabHDV.Controls.Add(this.txtHDVMa);
            this.lbl9.Name = "lbl9";
            this.lbl9.Location = new System.Drawing.Point(260, 245);
            this.lbl9.Text = "Họ tên:";
            this.lbl9.AutoSize = true;
            this.tabHDV.Controls.Add(this.lbl9);
            this.txtHDVTen.Name = "txtHDVTen";
            this.txtHDVTen.Location = new System.Drawing.Point(330, 242);
            this.txtHDVTen.Size = new System.Drawing.Size(240, 22);
            this.tabHDV.Controls.Add(this.txtHDVTen);
            this.lbl10.Name = "lbl10";
            this.lbl10.Location = new System.Drawing.Point(15, 280);
            this.lbl10.Text = "Điện thoại:";
            this.lbl10.AutoSize = true;
            this.tabHDV.Controls.Add(this.lbl10);
            this.txtHDVDT.Name = "txtHDVDT";
            this.txtHDVDT.Location = new System.Drawing.Point(100, 277);
            this.txtHDVDT.Size = new System.Drawing.Size(150, 22);
            this.tabHDV.Controls.Add(this.txtHDVDT);
            this.lbl11.Name = "lbl11";
            this.lbl11.Location = new System.Drawing.Point(260, 280);
            this.lbl11.Text = "Lương căn bản:";
            this.lbl11.AutoSize = true;
            this.tabHDV.Controls.Add(this.lbl11);
            this.numLuong.Name = "numLuong";
            this.numLuong.Location = new System.Drawing.Point(355, 277);
            this.numLuong.Size = new System.Drawing.Size(130, 22);
            this.numLuong.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            this.numLuong.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numLuong.Value = new decimal(new int[] { 0, 0, 0, 0 });
            this.numLuong.ThousandsSeparator = true;
            this.tabHDV.Controls.Add(this.numLuong);
            this.btnThemHDV.Name = "btnThemHDV";
            this.btnThemHDV.Location = new System.Drawing.Point(600, 272);
            this.btnThemHDV.Size = new System.Drawing.Size(100, 30);
            this.btnThemHDV.Text = "Thêm";
            this.btnThemHDV.UseVisualStyleBackColor = true;
            this.tabHDV.Controls.Add(this.btnThemHDV);
            this.dgvDTQ.Name = "dgvDTQ";
            this.dgvDTQ.Location = new System.Drawing.Point(10, 10);
            this.dgvDTQ.Size = new System.Drawing.Size(750, 200);
            this.dgvDTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDTQ.MultiSelect = false;
            this.dgvDTQ.AllowUserToDeleteRows = false;
            this.dgvDTQ.AllowUserToAddRows = false;
            this.dgvDTQ.ReadOnly = true;
            this.tabDTQ.Controls.Add(this.dgvDTQ);
            this.lbl12.Name = "lbl12";
            this.lbl12.Location = new System.Drawing.Point(15, 225);
            this.lbl12.Text = "Mã điểm TQ:";
            this.lbl12.AutoSize = true;
            this.tabDTQ.Controls.Add(this.lbl12);
            this.txtDTQMa.Name = "txtDTQMa";
            this.txtDTQMa.Location = new System.Drawing.Point(100, 222);
            this.txtDTQMa.Size = new System.Drawing.Size(120, 22);
            this.tabDTQ.Controls.Add(this.txtDTQMa);
            this.lbl13.Name = "lbl13";
            this.lbl13.Location = new System.Drawing.Point(260, 225);
            this.lbl13.Text = "Tên điểm TQ:";
            this.lbl13.AutoSize = true;
            this.tabDTQ.Controls.Add(this.lbl13);
            this.txtDTQTen.Name = "txtDTQTen";
            this.txtDTQTen.Location = new System.Drawing.Point(350, 222);
            this.txtDTQTen.Size = new System.Drawing.Size(220, 22);
            this.tabDTQ.Controls.Add(this.txtDTQTen);
            this.lbl14.Name = "lbl14";
            this.lbl14.Location = new System.Drawing.Point(15, 260);
            this.lbl14.Text = "Địa điểm:";
            this.lbl14.AutoSize = true;
            this.tabDTQ.Controls.Add(this.lbl14);
            this.txtDTQDiaDiem.Name = "txtDTQDiaDiem";
            this.txtDTQDiaDiem.Location = new System.Drawing.Point(100, 257);
            this.txtDTQDiaDiem.Size = new System.Drawing.Size(470, 22);
            this.tabDTQ.Controls.Add(this.txtDTQDiaDiem);
            this.lbl15.Name = "lbl15";
            this.lbl15.Location = new System.Drawing.Point(15, 295);
            this.lbl15.Text = "Nội dung:";
            this.lbl15.AutoSize = true;
            this.tabDTQ.Controls.Add(this.lbl15);
            this.txtDTQNoiDung.Name = "txtDTQNoiDung";
            this.txtDTQNoiDung.Location = new System.Drawing.Point(100, 292);
            this.txtDTQNoiDung.Size = new System.Drawing.Size(470, 22);
            this.tabDTQ.Controls.Add(this.txtDTQNoiDung);
            this.lbl16.Name = "lbl16";
            this.lbl16.Location = new System.Drawing.Point(15, 330);
            this.lbl16.Text = "Ý nghĩa:";
            this.lbl16.AutoSize = true;
            this.tabDTQ.Controls.Add(this.lbl16);
            this.txtDTQYNghia.Name = "txtDTQYNghia";
            this.txtDTQYNghia.Location = new System.Drawing.Point(100, 327);
            this.txtDTQYNghia.Size = new System.Drawing.Size(470, 22);
            this.tabDTQ.Controls.Add(this.txtDTQYNghia);
            this.btnThemDTQ.Name = "btnThemDTQ";
            this.btnThemDTQ.Location = new System.Drawing.Point(600, 290);
            this.btnThemDTQ.Size = new System.Drawing.Size(100, 30);
            this.btnThemDTQ.Text = "Thêm";
            this.btnThemDTQ.UseVisualStyleBackColor = true;
            this.tabDTQ.Controls.Add(this.btnThemDTQ);
            this.btnDong.Name = "btnDong";
            this.btnDong.Location = new System.Drawing.Point(690, 475);
            this.btnDong.Size = new System.Drawing.Size(100, 30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.Controls.Add(this.btnDong);
            this.btnThemPT.Click += new System.EventHandler(this.btnThemPT_Click);
            this.btnThemDB.Click += new System.EventHandler(this.btnThemDB_Click);
            this.btnThemHDV.Click += new System.EventHandler(this.btnThemHDV_Click);
            this.btnThemDTQ.Click += new System.EventHandler(this.btnThemDTQ_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 520);
            this.Name = "FrmDanhMuc";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Danh mục";
            this.Load += new System.EventHandler(this.FrmDanhMuc_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvPT)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvHDV)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numLuong)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDTQ)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.TabControl tabDanhMuc;
        private System.Windows.Forms.TabPage tabPT;
        private System.Windows.Forms.TabPage tabDB;
        private System.Windows.Forms.TabPage tabHDV;
        private System.Windows.Forms.TabPage tabDTQ;
        private System.Windows.Forms.DataGridView dgvPT;
        private System.Windows.Forms.Label lbl1;
        private System.Windows.Forms.TextBox txtPTMa;
        private System.Windows.Forms.Label lbl2;
        private System.Windows.Forms.TextBox txtPTTen;
        private System.Windows.Forms.Label lbl3;
        private System.Windows.Forms.TextBox txtPTGhiChu;
        private System.Windows.Forms.Button btnThemPT;
        private System.Windows.Forms.DataGridView dgvDB;
        private System.Windows.Forms.Label lbl4;
        private System.Windows.Forms.TextBox txtDBMa;
        private System.Windows.Forms.Label lbl5;
        private System.Windows.Forms.TextBox txtDBTen;
        private System.Windows.Forms.Label lbl6;
        private System.Windows.Forms.TextBox txtDBDiaChi;
        private System.Windows.Forms.Label lbl7;
        private System.Windows.Forms.TextBox txtDBDT;
        private System.Windows.Forms.Button btnThemDB;
        private System.Windows.Forms.DataGridView dgvHDV;
        private System.Windows.Forms.Label lbl8;
        private System.Windows.Forms.TextBox txtHDVMa;
        private System.Windows.Forms.Label lbl9;
        private System.Windows.Forms.TextBox txtHDVTen;
        private System.Windows.Forms.Label lbl10;
        private System.Windows.Forms.TextBox txtHDVDT;
        private System.Windows.Forms.Label lbl11;
        private System.Windows.Forms.NumericUpDown numLuong;
        private System.Windows.Forms.Button btnThemHDV;
        private System.Windows.Forms.DataGridView dgvDTQ;
        private System.Windows.Forms.Label lbl12;
        private System.Windows.Forms.TextBox txtDTQMa;
        private System.Windows.Forms.Label lbl13;
        private System.Windows.Forms.TextBox txtDTQTen;
        private System.Windows.Forms.Label lbl14;
        private System.Windows.Forms.TextBox txtDTQDiaDiem;
        private System.Windows.Forms.Label lbl15;
        private System.Windows.Forms.TextBox txtDTQNoiDung;
        private System.Windows.Forms.Label lbl16;
        private System.Windows.Forms.TextBox txtDTQYNghia;
        private System.Windows.Forms.Button btnThemDTQ;
        private System.Windows.Forms.Button btnDong;
    }
}
