namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmKetThucKhaoSat
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tabKT = new System.Windows.Forms.TabControl();
            this.tabTT = new System.Windows.Forms.TabPage();
            this.tabKS = new System.Windows.Forms.TabPage();
            this.dgvDoan = new System.Windows.Forms.DataGridView();
            this.lbl1 = new System.Windows.Forms.Label();
            this.txtSoTT = new System.Windows.Forms.TextBox();
            this.lbl2 = new System.Windows.Forms.Label();
            this.txtSoDK = new System.Windows.Forms.TextBox();
            this.lbl3 = new System.Windows.Forms.Label();
            this.dtTT = new System.Windows.Forms.DateTimePicker();
            this.lbl4 = new System.Windows.Forms.Label();
            this.numTien = new System.Windows.Forms.NumericUpDown();
            this.lbl5 = new System.Windows.Forms.Label();
            this.txtGhiChu = new System.Windows.Forms.TextBox();
            this.btnThanhToan = new System.Windows.Forms.Button();
            this.lbl6 = new System.Windows.Forms.Label();
            this.cboLoaiKS = new System.Windows.Forms.ComboBox();
            this.lbl7 = new System.Windows.Forms.Label();
            this.cboDangKy = new System.Windows.Forms.ComboBox();
            this.lbl8 = new System.Windows.Forms.Label();
            this.txtMaKS = new System.Windows.Forms.TextBox();
            this.lbl9 = new System.Windows.Forms.Label();
            this.dtGui = new System.Windows.Forms.DateTimePicker();
            this.btnGui = new System.Windows.Forms.Button();
            this.dgvKS = new System.Windows.Forms.DataGridView();
            this.lbl10 = new System.Windows.Forms.Label();
            this.txtKSChon = new System.Windows.Forms.TextBox();
            this.lbl11 = new System.Windows.Forms.Label();
            this.dtPH = new System.Windows.Forms.DateTimePicker();
            this.lbl12 = new System.Windows.Forms.Label();
            this.numDiem = new System.Windows.Forms.NumericUpDown();
            this.lbl13 = new System.Windows.Forms.Label();
            this.txtGopY = new System.Windows.Forms.TextBox();
            this.btnGhiPH = new System.Windows.Forms.Button();
            this.btnDong = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDoan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numTien)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDiem)).BeginInit();
            this.SuspendLayout();
            this.tabKT.Name = "tabKT";
            this.tabKT.Location = new System.Drawing.Point(10, 10);
            this.tabKT.Size = new System.Drawing.Size(900, 560);
            this.Controls.Add(this.tabKT);
            this.tabTT.Name = "tabTT";
            this.tabTT.Location = new System.Drawing.Point(4, 22);
            this.tabTT.Size = new System.Drawing.Size(892, 534);
            this.tabTT.Text = "Thanh toán sau tour (đoàn)";
            this.tabTT.UseVisualStyleBackColor = true;
            this.tabTT.Padding = new System.Windows.Forms.Padding(3);
            this.tabKT.Controls.Add(this.tabTT);
            this.tabKS.Name = "tabKS";
            this.tabKS.Location = new System.Drawing.Point(4, 22);
            this.tabKS.Size = new System.Drawing.Size(892, 534);
            this.tabKS.Text = "Khảo sát khách hàng";
            this.tabKS.UseVisualStyleBackColor = true;
            this.tabKS.Padding = new System.Windows.Forms.Padding(3);
            this.tabKT.Controls.Add(this.tabKS);
            this.dgvDoan.Name = "dgvDoan";
            this.dgvDoan.Location = new System.Drawing.Point(10, 10);
            this.dgvDoan.Size = new System.Drawing.Size(870, 360);
            this.dgvDoan.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDoan.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDoan.MultiSelect = false;
            this.dgvDoan.AllowUserToDeleteRows = false;
            this.dgvDoan.AllowUserToAddRows = false;
            this.dgvDoan.ReadOnly = true;
            this.tabTT.Controls.Add(this.dgvDoan);
            this.lbl1.Name = "lbl1";
            this.lbl1.Location = new System.Drawing.Point(15, 392);
            this.lbl1.Text = "Số thanh toán:";
            this.lbl1.AutoSize = true;
            this.tabTT.Controls.Add(this.lbl1);
            this.txtSoTT.Name = "txtSoTT";
            this.txtSoTT.Location = new System.Drawing.Point(105, 389);
            this.txtSoTT.Size = new System.Drawing.Size(130, 22);
            this.tabTT.Controls.Add(this.txtSoTT);
            this.lbl2.Name = "lbl2";
            this.lbl2.Location = new System.Drawing.Point(270, 392);
            this.lbl2.Text = "Phiếu đoàn:";
            this.lbl2.AutoSize = true;
            this.tabTT.Controls.Add(this.lbl2);
            this.txtSoDK.Name = "txtSoDK";
            this.txtSoDK.Location = new System.Drawing.Point(345, 389);
            this.txtSoDK.Size = new System.Drawing.Size(130, 22);
            this.txtSoDK.ReadOnly = true;
            this.tabTT.Controls.Add(this.txtSoDK);
            this.lbl3.Name = "lbl3";
            this.lbl3.Location = new System.Drawing.Point(510, 392);
            this.lbl3.Text = "Ngày thanh toán:";
            this.lbl3.AutoSize = true;
            this.tabTT.Controls.Add(this.lbl3);
            this.dtTT.Name = "dtTT";
            this.dtTT.Location = new System.Drawing.Point(610, 389);
            this.dtTT.Size = new System.Drawing.Size(130, 22);
            this.dtTT.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.tabTT.Controls.Add(this.dtTT);
            this.lbl4.Name = "lbl4";
            this.lbl4.Location = new System.Drawing.Point(15, 430);
            this.lbl4.Text = "Số tiền:";
            this.lbl4.AutoSize = true;
            this.tabTT.Controls.Add(this.lbl4);
            this.numTien.Name = "numTien";
            this.numTien.Location = new System.Drawing.Point(105, 427);
            this.numTien.Size = new System.Drawing.Size(130, 22);
            this.numTien.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            this.numTien.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numTien.Value = new decimal(new int[] { 0, 0, 0, 0 });
            this.numTien.ThousandsSeparator = true;
            this.tabTT.Controls.Add(this.numTien);
            this.lbl5.Name = "lbl5";
            this.lbl5.Location = new System.Drawing.Point(270, 430);
            this.lbl5.Text = "Ghi chú:";
            this.lbl5.AutoSize = true;
            this.tabTT.Controls.Add(this.lbl5);
            this.txtGhiChu.Name = "txtGhiChu";
            this.txtGhiChu.Location = new System.Drawing.Point(345, 427);
            this.txtGhiChu.Size = new System.Drawing.Size(395, 22);
            this.tabTT.Controls.Add(this.txtGhiChu);
            this.btnThanhToan.Name = "btnThanhToan";
            this.btnThanhToan.Location = new System.Drawing.Point(750, 420);
            this.btnThanhToan.Size = new System.Drawing.Size(120, 36);
            this.btnThanhToan.Text = "Ghi nhận thanh toán";
            this.btnThanhToan.UseVisualStyleBackColor = true;
            this.tabTT.Controls.Add(this.btnThanhToan);
            this.lbl6.Name = "lbl6";
            this.lbl6.Location = new System.Drawing.Point(15, 18);
            this.lbl6.Text = "Loại khách:";
            this.lbl6.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl6);
            this.cboLoaiKS.Name = "cboLoaiKS";
            this.cboLoaiKS.Location = new System.Drawing.Point(85, 15);
            this.cboLoaiKS.Size = new System.Drawing.Size(90, 22);
            this.cboLoaiKS.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLoaiKS.FormattingEnabled = true;
            this.tabKS.Controls.Add(this.cboLoaiKS);
            this.lbl7.Name = "lbl7";
            this.lbl7.Location = new System.Drawing.Point(195, 18);
            this.lbl7.Text = "Đăng ký đã kết thúc:";
            this.lbl7.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl7);
            this.cboDangKy.Name = "cboDangKy";
            this.cboDangKy.Location = new System.Drawing.Point(305, 15);
            this.cboDangKy.Size = new System.Drawing.Size(330, 22);
            this.cboDangKy.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDangKy.FormattingEnabled = true;
            this.tabKS.Controls.Add(this.cboDangKy);
            this.lbl8.Name = "lbl8";
            this.lbl8.Location = new System.Drawing.Point(660, 18);
            this.lbl8.Text = "Mã KS:";
            this.lbl8.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl8);
            this.txtMaKS.Name = "txtMaKS";
            this.txtMaKS.Location = new System.Drawing.Point(705, 15);
            this.txtMaKS.Size = new System.Drawing.Size(110, 22);
            this.tabKS.Controls.Add(this.txtMaKS);
            this.lbl9.Name = "lbl9";
            this.lbl9.Location = new System.Drawing.Point(15, 53);
            this.lbl9.Text = "Ngày gửi:";
            this.lbl9.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl9);
            this.dtGui.Name = "dtGui";
            this.dtGui.Location = new System.Drawing.Point(85, 50);
            this.dtGui.Size = new System.Drawing.Size(130, 22);
            this.dtGui.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.tabKS.Controls.Add(this.dtGui);
            this.btnGui.Name = "btnGui";
            this.btnGui.Location = new System.Drawing.Point(700, 45);
            this.btnGui.Size = new System.Drawing.Size(150, 30);
            this.btnGui.Text = "Gửi phiếu khảo sát";
            this.btnGui.UseVisualStyleBackColor = true;
            this.tabKS.Controls.Add(this.btnGui);
            this.dgvKS.Name = "dgvKS";
            this.dgvKS.Location = new System.Drawing.Point(10, 90);
            this.dgvKS.Size = new System.Drawing.Size(870, 300);
            this.dgvKS.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvKS.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvKS.MultiSelect = false;
            this.dgvKS.AllowUserToDeleteRows = false;
            this.dgvKS.AllowUserToAddRows = false;
            this.dgvKS.ReadOnly = true;
            this.tabKS.Controls.Add(this.dgvKS);
            this.lbl10.Name = "lbl10";
            this.lbl10.Location = new System.Drawing.Point(15, 413);
            this.lbl10.Text = "Phiếu chọn:";
            this.lbl10.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl10);
            this.txtKSChon.Name = "txtKSChon";
            this.txtKSChon.Location = new System.Drawing.Point(90, 410);
            this.txtKSChon.Size = new System.Drawing.Size(110, 22);
            this.txtKSChon.ReadOnly = true;
            this.tabKS.Controls.Add(this.txtKSChon);
            this.lbl11.Name = "lbl11";
            this.lbl11.Location = new System.Drawing.Point(235, 413);
            this.lbl11.Text = "Ngày phản hồi:";
            this.lbl11.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl11);
            this.dtPH.Name = "dtPH";
            this.dtPH.Location = new System.Drawing.Point(325, 410);
            this.dtPH.Size = new System.Drawing.Size(130, 22);
            this.dtPH.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.tabKS.Controls.Add(this.dtPH);
            this.lbl12.Name = "lbl12";
            this.lbl12.Location = new System.Drawing.Point(490, 413);
            this.lbl12.Text = "Điểm (1-5):";
            this.lbl12.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl12);
            this.numDiem.Name = "numDiem";
            this.numDiem.Location = new System.Drawing.Point(560, 410);
            this.numDiem.Size = new System.Drawing.Size(60, 22);
            this.numDiem.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numDiem.Maximum = new decimal(new int[] { 5, 0, 0, 0 });
            this.numDiem.Value = new decimal(new int[] { 5, 0, 0, 0 });
            this.tabKS.Controls.Add(this.numDiem);
            this.lbl13.Name = "lbl13";
            this.lbl13.Location = new System.Drawing.Point(15, 448);
            this.lbl13.Text = "Góp ý:";
            this.lbl13.AutoSize = true;
            this.tabKS.Controls.Add(this.lbl13);
            this.txtGopY.Name = "txtGopY";
            this.txtGopY.Location = new System.Drawing.Point(90, 445);
            this.txtGopY.Size = new System.Drawing.Size(530, 22);
            this.tabKS.Controls.Add(this.txtGopY);
            this.btnGhiPH.Name = "btnGhiPH";
            this.btnGhiPH.Location = new System.Drawing.Point(700, 440);
            this.btnGhiPH.Size = new System.Drawing.Size(150, 30);
            this.btnGhiPH.Text = "Ghi nhận góp ý";
            this.btnGhiPH.UseVisualStyleBackColor = true;
            this.tabKS.Controls.Add(this.btnGhiPH);
            this.btnDong.Name = "btnDong";
            this.btnDong.Location = new System.Drawing.Point(810, 578);
            this.btnDong.Size = new System.Drawing.Size(100, 30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.Controls.Add(this.btnDong);
            this.dgvDoan.SelectionChanged += new System.EventHandler(this.dgvDoan_SelectionChanged);
            this.btnThanhToan.Click += new System.EventHandler(this.btnThanhToan_Click);
            this.cboLoaiKS.SelectedIndexChanged += new System.EventHandler(this.cboLoaiKS_SelectedIndexChanged);
            this.btnGui.Click += new System.EventHandler(this.btnGui_Click);
            this.dgvKS.SelectionChanged += new System.EventHandler(this.dgvKS_SelectionChanged);
            this.btnGhiPH.Click += new System.EventHandler(this.btnGhiPH_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(920, 620);
            this.Name = "FrmKetThucKhaoSat";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Kết thúc tour - thanh toán đoàn - khảo sát";
            this.Load += new System.EventHandler(this.FrmKetThucKhaoSat_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDoan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numTien)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKS)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDiem)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.TabControl tabKT;
        private System.Windows.Forms.TabPage tabTT;
        private System.Windows.Forms.TabPage tabKS;
        private System.Windows.Forms.DataGridView dgvDoan;
        private System.Windows.Forms.Label lbl1;
        private System.Windows.Forms.TextBox txtSoTT;
        private System.Windows.Forms.Label lbl2;
        private System.Windows.Forms.TextBox txtSoDK;
        private System.Windows.Forms.Label lbl3;
        private System.Windows.Forms.DateTimePicker dtTT;
        private System.Windows.Forms.Label lbl4;
        private System.Windows.Forms.NumericUpDown numTien;
        private System.Windows.Forms.Label lbl5;
        private System.Windows.Forms.TextBox txtGhiChu;
        private System.Windows.Forms.Button btnThanhToan;
        private System.Windows.Forms.Label lbl6;
        private System.Windows.Forms.ComboBox cboLoaiKS;
        private System.Windows.Forms.Label lbl7;
        private System.Windows.Forms.ComboBox cboDangKy;
        private System.Windows.Forms.Label lbl8;
        private System.Windows.Forms.TextBox txtMaKS;
        private System.Windows.Forms.Label lbl9;
        private System.Windows.Forms.DateTimePicker dtGui;
        private System.Windows.Forms.Button btnGui;
        private System.Windows.Forms.DataGridView dgvKS;
        private System.Windows.Forms.Label lbl10;
        private System.Windows.Forms.TextBox txtKSChon;
        private System.Windows.Forms.Label lbl11;
        private System.Windows.Forms.DateTimePicker dtPH;
        private System.Windows.Forms.Label lbl12;
        private System.Windows.Forms.NumericUpDown numDiem;
        private System.Windows.Forms.Label lbl13;
        private System.Windows.Forms.TextBox txtGopY;
        private System.Windows.Forms.Button btnGhiPH;
        private System.Windows.Forms.Button btnDong;
    }
}
