namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmTour
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.lbl1 = new System.Windows.Forms.Label();
            this.cboTour = new System.Windows.Forms.ComboBox();
            this.tabTour = new System.Windows.Forms.TabControl();
            this.tabT = new System.Windows.Forms.TabPage();
            this.tabDD = new System.Windows.Forms.TabPage();
            this.tabCh = new System.Windows.Forms.TabPage();
            this.tabTQ = new System.Windows.Forms.TabPage();
            this.dgvTour = new System.Windows.Forms.DataGridView();
            this.lbl2 = new System.Windows.Forms.Label();
            this.txtMa = new System.Windows.Forms.TextBox();
            this.lbl3 = new System.Windows.Forms.Label();
            this.txtTen = new System.Windows.Forms.TextBox();
            this.lbl4 = new System.Windows.Forms.Label();
            this.numNgay = new System.Windows.Forms.NumericUpDown();
            this.lbl5 = new System.Windows.Forms.Label();
            this.numDem = new System.Windows.Forms.NumericUpDown();
            this.lbl6 = new System.Windows.Forms.Label();
            this.numGia = new System.Windows.Forms.NumericUpDown();
            this.lbl7 = new System.Windows.Forms.Label();
            this.txtMoTa = new System.Windows.Forms.TextBox();
            this.btnThemTour = new System.Windows.Forms.Button();
            this.dgvDiemDung = new System.Windows.Forms.DataGridView();
            this.lbl8 = new System.Windows.Forms.Label();
            this.numThuTu = new System.Windows.Forms.NumericUpDown();
            this.lbl9 = new System.Windows.Forms.Label();
            this.txtDiemDung = new System.Windows.Forms.TextBox();
            this.chkDoiPT = new System.Windows.Forms.CheckBox();
            this.chkAn = new System.Windows.Forms.CheckBox();
            this.chkKS = new System.Windows.Forms.CheckBox();
            this.lbl10 = new System.Windows.Forms.Label();
            this.numSao = new System.Windows.Forms.NumericUpDown();
            this.lbl11 = new System.Windows.Forms.Label();
            this.txtGhiChuDD = new System.Windows.Forms.TextBox();
            this.btnThemDD = new System.Windows.Forms.Button();
            this.dgvChang = new System.Windows.Forms.DataGridView();
            this.lbl12 = new System.Windows.Forms.Label();
            this.numChang = new System.Windows.Forms.NumericUpDown();
            this.lbl13 = new System.Windows.Forms.Label();
            this.cboPT = new System.Windows.Forms.ComboBox();
            this.lbl14 = new System.Windows.Forms.Label();
            this.txtGhiChuPT = new System.Windows.Forms.TextBox();
            this.btnThemChang = new System.Windows.Forms.Button();
            this.dgvTQ = new System.Windows.Forms.DataGridView();
            this.lbl15 = new System.Windows.Forms.Label();
            this.cboDTQ = new System.Windows.Forms.ComboBox();
            this.lbl16 = new System.Windows.Forms.Label();
            this.numThuTuTQ = new System.Windows.Forms.NumericUpDown();
            this.btnThemTQ = new System.Windows.Forms.Button();
            this.btnDong = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTour)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numNgay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGia)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDiemDung)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numThuTu)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSao)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvChang)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numChang)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTQ)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numThuTuTQ)).BeginInit();
            this.SuspendLayout();
            this.lbl1.Name = "lbl1";
            this.lbl1.Location = new System.Drawing.Point(10, 18);
            this.lbl1.Text = "Tour đang chọn (cho các tab hành trình):";
            this.lbl1.AutoSize = true;
            this.Controls.Add(this.lbl1);
            this.cboTour.Name = "cboTour";
            this.cboTour.Location = new System.Drawing.Point(270, 14);
            this.cboTour.Size = new System.Drawing.Size(300, 22);
            this.cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTour.FormattingEnabled = true;
            this.Controls.Add(this.cboTour);
            this.tabTour.Name = "tabTour";
            this.tabTour.Location = new System.Drawing.Point(10, 50);
            this.tabTour.Size = new System.Drawing.Size(880, 500);
            this.Controls.Add(this.tabTour);
            this.tabT.Name = "tabT";
            this.tabT.Location = new System.Drawing.Point(4, 22);
            this.tabT.Size = new System.Drawing.Size(872, 474);
            this.tabT.Text = "Tour";
            this.tabT.UseVisualStyleBackColor = true;
            this.tabT.Padding = new System.Windows.Forms.Padding(3);
            this.tabTour.Controls.Add(this.tabT);
            this.tabDD.Name = "tabDD";
            this.tabDD.Location = new System.Drawing.Point(4, 22);
            this.tabDD.Size = new System.Drawing.Size(872, 474);
            this.tabDD.Text = "Điểm dừng";
            this.tabDD.UseVisualStyleBackColor = true;
            this.tabDD.Padding = new System.Windows.Forms.Padding(3);
            this.tabTour.Controls.Add(this.tabDD);
            this.tabCh.Name = "tabCh";
            this.tabCh.Location = new System.Drawing.Point(4, 22);
            this.tabCh.Size = new System.Drawing.Size(872, 474);
            this.tabCh.Text = "Phương tiện theo chặng";
            this.tabCh.UseVisualStyleBackColor = true;
            this.tabCh.Padding = new System.Windows.Forms.Padding(3);
            this.tabTour.Controls.Add(this.tabCh);
            this.tabTQ.Name = "tabTQ";
            this.tabTQ.Location = new System.Drawing.Point(4, 22);
            this.tabTQ.Size = new System.Drawing.Size(872, 474);
            this.tabTQ.Text = "Điểm tham quan";
            this.tabTQ.UseVisualStyleBackColor = true;
            this.tabTQ.Padding = new System.Windows.Forms.Padding(3);
            this.tabTour.Controls.Add(this.tabTQ);
            this.dgvTour.Name = "dgvTour";
            this.dgvTour.Location = new System.Drawing.Point(10, 10);
            this.dgvTour.Size = new System.Drawing.Size(850, 320);
            this.dgvTour.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTour.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvTour.MultiSelect = false;
            this.dgvTour.AllowUserToDeleteRows = false;
            this.dgvTour.AllowUserToAddRows = false;
            this.dgvTour.ReadOnly = true;
            this.tabT.Controls.Add(this.dgvTour);
            this.lbl2.Name = "lbl2";
            this.lbl2.Location = new System.Drawing.Point(15, 350);
            this.lbl2.Text = "Mã tour:";
            this.lbl2.AutoSize = true;
            this.tabT.Controls.Add(this.lbl2);
            this.txtMa.Name = "txtMa";
            this.txtMa.Location = new System.Drawing.Point(90, 347);
            this.txtMa.Size = new System.Drawing.Size(120, 22);
            this.tabT.Controls.Add(this.txtMa);
            this.lbl3.Name = "lbl3";
            this.lbl3.Location = new System.Drawing.Point(260, 350);
            this.lbl3.Text = "Tên tour:";
            this.lbl3.AutoSize = true;
            this.tabT.Controls.Add(this.lbl3);
            this.txtTen.Name = "txtTen";
            this.txtTen.Location = new System.Drawing.Point(330, 347);
            this.txtTen.Size = new System.Drawing.Size(330, 22);
            this.tabT.Controls.Add(this.txtTen);
            this.lbl4.Name = "lbl4";
            this.lbl4.Location = new System.Drawing.Point(15, 385);
            this.lbl4.Text = "Số ngày:";
            this.lbl4.AutoSize = true;
            this.tabT.Controls.Add(this.lbl4);
            this.numNgay.Name = "numNgay";
            this.numNgay.Location = new System.Drawing.Point(90, 382);
            this.numNgay.Size = new System.Drawing.Size(70, 22);
            this.numNgay.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numNgay.Maximum = new decimal(new int[] { 60, 0, 0, 0 });
            this.numNgay.Value = new decimal(new int[] { 1, 0, 0, 0 });
            this.tabT.Controls.Add(this.numNgay);
            this.lbl5.Name = "lbl5";
            this.lbl5.Location = new System.Drawing.Point(260, 385);
            this.lbl5.Text = "Số đêm:";
            this.lbl5.AutoSize = true;
            this.tabT.Controls.Add(this.lbl5);
            this.numDem.Name = "numDem";
            this.numDem.Location = new System.Drawing.Point(330, 382);
            this.numDem.Size = new System.Drawing.Size(70, 22);
            this.numDem.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            this.numDem.Maximum = new decimal(new int[] { 60, 0, 0, 0 });
            this.numDem.Value = new decimal(new int[] { 0, 0, 0, 0 });
            this.tabT.Controls.Add(this.numDem);
            this.lbl6.Name = "lbl6";
            this.lbl6.Location = new System.Drawing.Point(450, 385);
            this.lbl6.Text = "Đơn giá / khách:";
            this.lbl6.AutoSize = true;
            this.tabT.Controls.Add(this.lbl6);
            this.numGia.Name = "numGia";
            this.numGia.Location = new System.Drawing.Point(550, 382);
            this.numGia.Size = new System.Drawing.Size(130, 22);
            this.numGia.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            this.numGia.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numGia.Value = new decimal(new int[] { 0, 0, 0, 0 });
            this.numGia.ThousandsSeparator = true;
            this.tabT.Controls.Add(this.numGia);
            this.lbl7.Name = "lbl7";
            this.lbl7.Location = new System.Drawing.Point(15, 420);
            this.lbl7.Text = "Mô tả:";
            this.lbl7.AutoSize = true;
            this.tabT.Controls.Add(this.lbl7);
            this.txtMoTa.Name = "txtMoTa";
            this.txtMoTa.Location = new System.Drawing.Point(90, 417);
            this.txtMoTa.Size = new System.Drawing.Size(570, 22);
            this.tabT.Controls.Add(this.txtMoTa);
            this.btnThemTour.Name = "btnThemTour";
            this.btnThemTour.Location = new System.Drawing.Point(720, 380);
            this.btnThemTour.Size = new System.Drawing.Size(120, 30);
            this.btnThemTour.Text = "Thêm tour";
            this.btnThemTour.UseVisualStyleBackColor = true;
            this.tabT.Controls.Add(this.btnThemTour);
            this.dgvDiemDung.Name = "dgvDiemDung";
            this.dgvDiemDung.Location = new System.Drawing.Point(10, 10);
            this.dgvDiemDung.Size = new System.Drawing.Size(850, 320);
            this.dgvDiemDung.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDiemDung.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDiemDung.MultiSelect = false;
            this.dgvDiemDung.AllowUserToDeleteRows = false;
            this.dgvDiemDung.AllowUserToAddRows = false;
            this.dgvDiemDung.ReadOnly = true;
            this.tabDD.Controls.Add(this.dgvDiemDung);
            this.lbl8.Name = "lbl8";
            this.lbl8.Location = new System.Drawing.Point(15, 350);
            this.lbl8.Text = "Thứ tự:";
            this.lbl8.AutoSize = true;
            this.tabDD.Controls.Add(this.lbl8);
            this.numThuTu.Name = "numThuTu";
            this.numThuTu.Location = new System.Drawing.Point(80, 347);
            this.numThuTu.Size = new System.Drawing.Size(70, 22);
            this.numThuTu.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numThuTu.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numThuTu.Value = new decimal(new int[] { 1, 0, 0, 0 });
            this.tabDD.Controls.Add(this.numThuTu);
            this.lbl9.Name = "lbl9";
            this.lbl9.Location = new System.Drawing.Point(190, 350);
            this.lbl9.Text = "Tên điểm dừng:";
            this.lbl9.AutoSize = true;
            this.tabDD.Controls.Add(this.lbl9);
            this.txtDiemDung.Name = "txtDiemDung";
            this.txtDiemDung.Location = new System.Drawing.Point(285, 347);
            this.txtDiemDung.Size = new System.Drawing.Size(250, 22);
            this.tabDD.Controls.Add(this.txtDiemDung);
            this.chkDoiPT.Name = "chkDoiPT";
            this.chkDoiPT.Location = new System.Drawing.Point(15, 385);
            this.chkDoiPT.Size = new System.Drawing.Size(130, 20);
            this.chkDoiPT.Text = "Đổi phương tiện";
            this.chkDoiPT.UseVisualStyleBackColor = true;
            this.tabDD.Controls.Add(this.chkDoiPT);
            this.chkAn.Name = "chkAn";
            this.chkAn.Location = new System.Drawing.Point(170, 385);
            this.chkAn.Size = new System.Drawing.Size(90, 20);
            this.chkAn.Text = "Có nơi ăn";
            this.chkAn.UseVisualStyleBackColor = true;
            this.tabDD.Controls.Add(this.chkAn);
            this.chkKS.Name = "chkKS";
            this.chkKS.Location = new System.Drawing.Point(280, 385);
            this.chkKS.Size = new System.Drawing.Size(110, 20);
            this.chkKS.Text = "Có khách sạn";
            this.chkKS.UseVisualStyleBackColor = true;
            this.tabDD.Controls.Add(this.chkKS);
            this.lbl10.Name = "lbl10";
            this.lbl10.Location = new System.Drawing.Point(420, 388);
            this.lbl10.Text = "Hạng sao:";
            this.lbl10.AutoSize = true;
            this.tabDD.Controls.Add(this.lbl10);
            this.numSao.Name = "numSao";
            this.numSao.Location = new System.Drawing.Point(485, 385);
            this.numSao.Size = new System.Drawing.Size(60, 22);
            this.numSao.Minimum = new decimal(new int[] { 2, 0, 0, 0 });
            this.numSao.Maximum = new decimal(new int[] { 5, 0, 0, 0 });
            this.numSao.Value = new decimal(new int[] { 3, 0, 0, 0 });
            this.numSao.Enabled = false;
            this.tabDD.Controls.Add(this.numSao);
            this.lbl11.Name = "lbl11";
            this.lbl11.Location = new System.Drawing.Point(15, 420);
            this.lbl11.Text = "Ghi chú:";
            this.lbl11.AutoSize = true;
            this.tabDD.Controls.Add(this.lbl11);
            this.txtGhiChuDD.Name = "txtGhiChuDD";
            this.txtGhiChuDD.Location = new System.Drawing.Point(80, 417);
            this.txtGhiChuDD.Size = new System.Drawing.Size(480, 22);
            this.tabDD.Controls.Add(this.txtGhiChuDD);
            this.btnThemDD.Name = "btnThemDD";
            this.btnThemDD.Location = new System.Drawing.Point(700, 380);
            this.btnThemDD.Size = new System.Drawing.Size(140, 30);
            this.btnThemDD.Text = "Thêm điểm dừng";
            this.btnThemDD.UseVisualStyleBackColor = true;
            this.tabDD.Controls.Add(this.btnThemDD);
            this.dgvChang.Name = "dgvChang";
            this.dgvChang.Location = new System.Drawing.Point(10, 10);
            this.dgvChang.Size = new System.Drawing.Size(850, 320);
            this.dgvChang.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvChang.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvChang.MultiSelect = false;
            this.dgvChang.AllowUserToDeleteRows = false;
            this.dgvChang.AllowUserToAddRows = false;
            this.dgvChang.ReadOnly = true;
            this.tabCh.Controls.Add(this.dgvChang);
            this.lbl12.Name = "lbl12";
            this.lbl12.Location = new System.Drawing.Point(15, 350);
            this.lbl12.Text = "Chặng thứ:";
            this.lbl12.AutoSize = true;
            this.tabCh.Controls.Add(this.lbl12);
            this.numChang.Name = "numChang";
            this.numChang.Location = new System.Drawing.Point(85, 347);
            this.numChang.Size = new System.Drawing.Size(70, 22);
            this.numChang.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numChang.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numChang.Value = new decimal(new int[] { 1, 0, 0, 0 });
            this.tabCh.Controls.Add(this.numChang);
            this.lbl13.Name = "lbl13";
            this.lbl13.Location = new System.Drawing.Point(200, 350);
            this.lbl13.Text = "Phương tiện:";
            this.lbl13.AutoSize = true;
            this.tabCh.Controls.Add(this.lbl13);
            this.cboPT.Name = "cboPT";
            this.cboPT.Location = new System.Drawing.Point(280, 347);
            this.cboPT.Size = new System.Drawing.Size(220, 22);
            this.cboPT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPT.FormattingEnabled = true;
            this.tabCh.Controls.Add(this.cboPT);
            this.lbl14.Name = "lbl14";
            this.lbl14.Location = new System.Drawing.Point(15, 385);
            this.lbl14.Text = "Ghi chú:";
            this.lbl14.AutoSize = true;
            this.tabCh.Controls.Add(this.lbl14);
            this.txtGhiChuPT.Name = "txtGhiChuPT";
            this.txtGhiChuPT.Location = new System.Drawing.Point(85, 382);
            this.txtGhiChuPT.Size = new System.Drawing.Size(480, 22);
            this.tabCh.Controls.Add(this.txtGhiChuPT);
            this.btnThemChang.Name = "btnThemChang";
            this.btnThemChang.Location = new System.Drawing.Point(700, 380);
            this.btnThemChang.Size = new System.Drawing.Size(140, 30);
            this.btnThemChang.Text = "Gắn phương tiện";
            this.btnThemChang.UseVisualStyleBackColor = true;
            this.tabCh.Controls.Add(this.btnThemChang);
            this.dgvTQ.Name = "dgvTQ";
            this.dgvTQ.Location = new System.Drawing.Point(10, 10);
            this.dgvTQ.Size = new System.Drawing.Size(850, 320);
            this.dgvTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvTQ.MultiSelect = false;
            this.dgvTQ.AllowUserToDeleteRows = false;
            this.dgvTQ.AllowUserToAddRows = false;
            this.dgvTQ.ReadOnly = true;
            this.tabTQ.Controls.Add(this.dgvTQ);
            this.lbl15.Name = "lbl15";
            this.lbl15.Location = new System.Drawing.Point(15, 350);
            this.lbl15.Text = "Điểm tham quan:";
            this.lbl15.AutoSize = true;
            this.tabTQ.Controls.Add(this.lbl15);
            this.cboDTQ.Name = "cboDTQ";
            this.cboDTQ.Location = new System.Drawing.Point(115, 347);
            this.cboDTQ.Size = new System.Drawing.Size(250, 22);
            this.cboDTQ.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDTQ.FormattingEnabled = true;
            this.tabTQ.Controls.Add(this.cboDTQ);
            this.lbl16.Name = "lbl16";
            this.lbl16.Location = new System.Drawing.Point(400, 350);
            this.lbl16.Text = "Thứ tự:";
            this.lbl16.AutoSize = true;
            this.tabTQ.Controls.Add(this.lbl16);
            this.numThuTuTQ.Name = "numThuTuTQ";
            this.numThuTuTQ.Location = new System.Drawing.Point(450, 347);
            this.numThuTuTQ.Size = new System.Drawing.Size(70, 22);
            this.numThuTuTQ.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numThuTuTQ.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numThuTuTQ.Value = new decimal(new int[] { 1, 0, 0, 0 });
            this.tabTQ.Controls.Add(this.numThuTuTQ);
            this.btnThemTQ.Name = "btnThemTQ";
            this.btnThemTQ.Location = new System.Drawing.Point(700, 345);
            this.btnThemTQ.Size = new System.Drawing.Size(140, 30);
            this.btnThemTQ.Text = "Gắn điểm TQ";
            this.btnThemTQ.UseVisualStyleBackColor = true;
            this.tabTQ.Controls.Add(this.btnThemTQ);
            this.btnDong.Name = "btnDong";
            this.btnDong.Location = new System.Drawing.Point(790, 560);
            this.btnDong.Size = new System.Drawing.Size(100, 30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.Controls.Add(this.btnDong);
            this.cboTour.SelectedIndexChanged += new System.EventHandler(this.cboTour_SelectedIndexChanged);
            this.btnThemTour.Click += new System.EventHandler(this.btnThemTour_Click);
            this.chkKS.CheckedChanged += new System.EventHandler(this.chkKS_CheckedChanged);
            this.btnThemDD.Click += new System.EventHandler(this.btnThemDD_Click);
            this.btnThemChang.Click += new System.EventHandler(this.btnThemChang_Click);
            this.btnThemTQ.Click += new System.EventHandler(this.btnThemTQ_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(900, 600);
            this.Name = "FrmTour";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Tour - hành trình";
            this.Load += new System.EventHandler(this.FrmTour_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvTour)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numNgay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGia)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDiemDung)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numThuTu)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSao)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvChang)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numChang)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTQ)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numThuTuTQ)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.Label lbl1;
        private System.Windows.Forms.ComboBox cboTour;
        private System.Windows.Forms.TabControl tabTour;
        private System.Windows.Forms.TabPage tabT;
        private System.Windows.Forms.TabPage tabDD;
        private System.Windows.Forms.TabPage tabCh;
        private System.Windows.Forms.TabPage tabTQ;
        private System.Windows.Forms.DataGridView dgvTour;
        private System.Windows.Forms.Label lbl2;
        private System.Windows.Forms.TextBox txtMa;
        private System.Windows.Forms.Label lbl3;
        private System.Windows.Forms.TextBox txtTen;
        private System.Windows.Forms.Label lbl4;
        private System.Windows.Forms.NumericUpDown numNgay;
        private System.Windows.Forms.Label lbl5;
        private System.Windows.Forms.NumericUpDown numDem;
        private System.Windows.Forms.Label lbl6;
        private System.Windows.Forms.NumericUpDown numGia;
        private System.Windows.Forms.Label lbl7;
        private System.Windows.Forms.TextBox txtMoTa;
        private System.Windows.Forms.Button btnThemTour;
        private System.Windows.Forms.DataGridView dgvDiemDung;
        private System.Windows.Forms.Label lbl8;
        private System.Windows.Forms.NumericUpDown numThuTu;
        private System.Windows.Forms.Label lbl9;
        private System.Windows.Forms.TextBox txtDiemDung;
        private System.Windows.Forms.CheckBox chkDoiPT;
        private System.Windows.Forms.CheckBox chkAn;
        private System.Windows.Forms.CheckBox chkKS;
        private System.Windows.Forms.Label lbl10;
        private System.Windows.Forms.NumericUpDown numSao;
        private System.Windows.Forms.Label lbl11;
        private System.Windows.Forms.TextBox txtGhiChuDD;
        private System.Windows.Forms.Button btnThemDD;
        private System.Windows.Forms.DataGridView dgvChang;
        private System.Windows.Forms.Label lbl12;
        private System.Windows.Forms.NumericUpDown numChang;
        private System.Windows.Forms.Label lbl13;
        private System.Windows.Forms.ComboBox cboPT;
        private System.Windows.Forms.Label lbl14;
        private System.Windows.Forms.TextBox txtGhiChuPT;
        private System.Windows.Forms.Button btnThemChang;
        private System.Windows.Forms.DataGridView dgvTQ;
        private System.Windows.Forms.Label lbl15;
        private System.Windows.Forms.ComboBox cboDTQ;
        private System.Windows.Forms.Label lbl16;
        private System.Windows.Forms.NumericUpDown numThuTuTQ;
        private System.Windows.Forms.Button btnThemTQ;
        private System.Windows.Forms.Button btnDong;
    }
}
